language: node_js
node_js:
 - "node"
script:
  - npm run buildTokens
  - npm run set-patch $TRAVIS_BUILD_ID
branches:
  only:
    - master
before_deploy:
  - npm run copyReadme
  - npm run copyPkg
  - npm run copyJson
  - npm run changelog
  - npm run concat
  - cd dist
deploy:
  on:
    branch: master
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
notifications:
  webhooks: https://outlook.office.com/webhook/47d2147c-afa1-4bd4-ae32-2749757844b2@0f44c5d4-42b0-45c2-bf55-d0fea8430d33/TravisCI/6ccc70bb60f948809957cbd7ab063223/c3c71b9e-d319-4002-a79c-b694111e2be8
